### ISSUE TITLE
using a custom model

### ISSUE THREAD

**Issue by jeyhunbay** [speaches-ai/speaches#174]
I have a fine-tuned model that converted it to faster-whisper format using the instructions in the faster-whisper repo. I can load that model with faster-whisper and it works. How to add that model to the server?
I tried changing the env variable WHISPER__MODEL to point to my model's path, but the model is not being picked up.
Any suggestions?
Thanks!

**Comment by jeyhunbay** [comment]
for now I just patched `list_whisper_models` in `faster_whisper_server/hf_utils.py` to inject my custom model to the list of available models. Probably not the most elegant solution, but it at least it works. But still looking for a better way of doing this.

**Comment by fedirz** [comment]
If you set the `HF_TOKEN` environment variable on HuggingFace, your private model should appear in the model list. However, loading a local model (not on HuggingFace) is currently unsupported. I plan to support this, but I am unsure when I'll have the time to add it.

**Comment by PierreMesure** [comment]
Hi, thank you for documenting this possibility here. I've tried to set HF_TOKEN without success:

```yaml
speaches:
    container_name: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    volumes:
      - ./speaches:/root/.cache/huggingface
    environment:
      # - WHISPER__MODEL=deepdml/faster-whisper-large-v3-turbo-ct2
      - WHISPER__MODEL=KBLab/kb-whisper-large-beta
      - HF_TOKEN=hf_xxx...
```

I'm trying to load [this model](https://huggingface.co/KBLab/kb-whisper-large-beta) but still getting the following stacktrace:

```
Traceback (most recent call last):

  File "/home/ubuntu/speaches/.venv/lib/python3.12/site-packages/gradio/queueing.py", line 622, in process_events

    response = await route_utils.call_process_api(

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/speaches/.venv/lib/python3.12/site-packages/gradio/route_utils.py", line 323, in call_process_api

    output = await app.get_blocks().process_api(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/speaches/.venv/lib/python3.12/site-packages/gradio/blocks.py", line 2016, in process_api

    result = await self.call_function(

             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/speaches/.venv/lib/python3.12/site-packages/gradio/blocks.py", line 1567, in call_function

    prediction = await fn(*processed_input)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/speaches/.venv/lib/python3.12/site-packages/gradio/utils.py", line 813, in async_wrapper

    response = await f(*args, **kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ubuntu/speaches/speaches/gradio_app.py", line 104, in update_whisper_model_dropdown

    assert config.whisper.model in model_names

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError
```
